### ISSUE TITLE
Get verify code automatically

### ISSUE THREAD

**Issue by fabriziomorello** [sachin-handiekar/jInstagram#100]
Is it possible to get the verify code (to generate the access token) automatically, i.e. without copying and pasting the Authorization URL in the browser and copying and pasting the related code in the console? I need to switch from an clientId to another one in case I reach the limit rate, but I'd like to switch without user interaction.

**Comment by k0balt0** [comment]
A nice way is to redirect the authorization url and capture it with another controller getting the code (with Spring MVC for example)

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
