### ISSUE TITLE
InstagramService and Instagram objects do not implement Serializable (but are added to session anyway)

### ISSUE THREAD

**Issue by BorysHN** [sachin-handiekar/jInstagram#101]
Hey Sachin,

Great product here. It's really been an enjoyment using it. 

I am currently building a spring application which makes use of the jInstagram library. Session management is very important for a secure application. 

In your example project you add two objects to the session.
`org.jinstagram.Instagram`
`org.jinstagram.auth.oauth.InstagramService`

However, this is in error. It's actually insecure, and prone to null pointer exception errors when retrieving objects from the session. Try running findbugs on code that adds an unserialized object to the session. Although it may work in your application, there is no session management built in. Things get finicky once using spring-session and redis session server. 

Is there anyway you could have those two classes implement the `java.io.Serializable` interface? They would only need a generated `serialVersionUID`. Or if you could provide an interface for those two classes, then I could implement my own serializable objects. I'd be happy to contribute to the project if I could get that tested and pushed to maven. 

I have tried to make some wrapper classes to handle this, but it's looking hacky. I could just pull out the classes from the jar and re-implement them, but I thought I would ask first, because technically that's another hack. 

Thanks,
Borys H.N.

**Comment by BorysHN** [comment]
I've been playing around with pulling out the classes, and It's not just a simple matter of updating two classes to implement the Serializable interface. I apologize for that. All classes which are recursive dependencies of `org.jinstagram.Instagram` and `org.jinstagram.auth.oauth.InstagramService` must implement Serializable. This would require a larger update to the project. Please let me know if you'd like to collaborate on this, I think it would be a great addition to the project, otherwise I will just decompile the jar and make all necessary changes.

**Comment by slumx** [comment]
I think this will be difficult. As an example The java.net.Proxy does not implement Serializable and is used by org.jinstagram.Instagram, probably more classes has the same issue.

the Instagram class on the other hand does not seem heavy to recreate so can't you just create a new instance when one is needed and then just save the user key etc. in the session?

**Comment by BorysHN** [comment]
That is a nice and quick solution, thank you for bringing simplicity to my attention. I could also use a spring bean with a singleton scope to hold the Instagram and InstagramService objects, didn't think of that earlier either. However, I'm still concerned about the core functionality of the library. Don't get me wrong here though, your work is really nice, and I'm so happy to have found your library.

I've found out some more information though...

After testing decompiling the `jInstagram-1.0.10.jar`, the only classes that need to implement `java.io.Serializable` are...

*  `org.jinstagram.Instagram`
*  `org.jinstagram.InstagramConfig`
*  `org.jinstagram.auth.InstagramApi`
*  `org.jinstagram.auth.model.OAuthConfig`
*  `org.jinstagram.oauth.InstagramService`

The code base for the `jInstagram-1.0.10.jar` seems to be a little different than what's on github, so that's the only reason I decompiled the jar. 

This is assuming you only want to keep track of Instagram and InstagramService in your session (as in your example project), which I think is a reasonable implementation.

**Comment by slumx** [comment]
The only thing a have against Serializable is that you're making a kind of binding contract which can be counter-productive for future changes.
We have been using it the way I described above for years in a multi user enviroment, and it works great. 
As you mention yourself you can ofcause just use a Spring bean if you only need to configure it once.

PS. I didn't write the library, I'm just a user as yourself :-)

**Comment by BorysHN** [comment]
@slumx I gotcha, thank you for the reassurance. I'm happy to hear a testimony. I'm probably being too apprehensive, but I've got it working and feel confident in the established codebase still. I'd be happy with an extensible interface approach to the library, it's good protocol for future design too, but that's still me being apprehensive.

**Comment by alatushkin** [comment]
@BorysHN I'am sure that there is no reason to store org.jinstagram.Instagram instance in session scope. It's better to store Token (which implements Serializable) in session or maybe some of your class wrap over Token.
So i think it's no an issue.

P.S Maybe that example confuse you but it was changed a year ago - so i think it's just outdated.

**Comment by BorysHN** [comment]
@alatushkin most certainly. Simplicity flew over my head. It's a non-issue.
