### ISSUE TITLE
Get the api secret from the InstagramService class

### ISSUE THREAD

**Issue by n-my** [sachin-handiekar/jInstagram#102]
When we create an `Instagram` object with enforce signed header we need the api secret.

The class `org.jinstagram.auth.oauth.InstagramService` has an `OAuthConfig` field which has a `getApiSecret()` method.
It would be nice to add a `getApiSecret()` method in the `InstagramService` class so we can directly get the api secret in a secure way.

The implementation is very simple but I'd like to know what you think about that first before submitting my PR.

**Comment by n-my** [comment]
Or even better we could add 2 new methods in `org.jinstagram.auth.oauth.InstagramService` : 
``` java
public Instagram getInstagram() {...}
public Instagram getSignedHeaderInstagram(String requestIpAddress)
```
to directly get an Instagram object without dealing with our token and secret.

**Comment by n-my** [comment]
my PR : 
https://github.com/sachin-handiekar/jInstagram/pull/103

**Comment by sachin-handiekar** [comment]
Thanks for the PR...
