### ISSUE TITLE
How to list ALL User liked media feed elements ?

### ISSUE THREAD

**Issue by gluon** [sachin-handiekar/jInstagram#104]
Hi there,
it seems there are 2 definitions of method getUserLikedMediaFeed() but I cannot find a way to get ALL the liked media list.

Is there a way please ?

**Comment by sembozdemir** [comment]
it gives a MediaFeed instance. You have to use pagination. 
e.g: 

    MediaFeed recentMediaNextPage = instagram.getRecentMediaNextPage(firstMediaFeed.getPagination());

This is example code of pagination:
https://github.com/sachin-handiekar/jInstagram-examples/blob/master/BasicWebDemo/src/main/webapp/search.jsp

**Comment by gluon** [comment]
perfect.
thanks a lot :)
