### ISSUE TITLE
Unknown error response code: 404

### ISSUE THREAD

**Issue by giomendo** [sachin-handiekar/jInstagram#105]
Hi Guys,

I´m having this error when trying to execute:  client.getRecentMediaTags(tag)
Don´t know if Instagram changed something on the url´s that the lib is calling.

It is also ocurring on the demo: 
http://jinstagram-sachinhandiekar.rhcloud.com/BasicWebDemo/search.jsp  

Trying to lookup some tags like: formandasfisioipa‬ or comendaveraprata  

Anybody had this problem yet?

**Comment by sembozdemir** [comment]
I also have this error when I try to call instagram.getRecentMediaNextPage(pagination)

**Comment by sachin-handiekar** [comment]
Related to #110

**Comment by carlosrivin** [comment]
Me and @giomendo found out what was the problem. It was an encoding problem when sending the String that we wanted to monitor. The string contained some bad characters on the end and sometimes also at the begging and that just made things break. Sorry for the inconvenience.

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
