### ISSUE TITLE
Remove logging dependencies from compile-scope

### ISSUE THREAD

**Issue by lbeuster** [sachin-handiekar/jInstagram#111]
Currently (v 1.1.3) the logging deps (slf4j-log4j12, jcl-over-slf4j, log4j) are in compile scope which means that everybody has them in his project. But often users want to use a different logging impl (e.g. logback).

Only slf4j-api should be kept in compile scope, all others should go to optional, provided or better test.

Best regards
Lars

**Comment by sachin-handiekar** [comment]
Fixed in the current build.
