### ISSUE TITLE
How to set a like in code ?

### ISSUE THREAD

**Issue by thuanitdn** [sachin-handiekar/jInstagram#116]
I have  the following code:
           Instagram instagram = (Instagram) req.getSession().getAttribute("instagram");
            LikesFeed feed = instagram.setUserLike("media_id");
But it's not working .

**Comment by sembozdemir** [comment]
You have to add scope when creating service.

    InstagramService service = new InstagramAuthService()
                            .apiKey("your_client_id")
                            .apiSecret("your_client_secret")
                            .callback("your_callback_url") 
                            .scope("likes")
                            .build();

But, if you want to like, comment or follow on behalf of the user. You have to apply for it to Instagram. Instagram have decided to block these features for an app that is able to be used by everyone. You can apply [this form](http://developers.instagram.com/post/116410697261/publishing-guidelines-and-signed-requests) to access these scopes. There is the [blog post](http://developers.instagram.com/post/116410697261/publishing-guidelines-and-signed-requests) about this situation on Instagram Developers Blog.

**Comment by marz619** [comment]
@sembozdemir please also see https://github.com/sachin-handiekar/jInstagram/issues/114#issuecomment-144767642

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
