### ISSUE TITLE
Enforcing Signed Requests

### ISSUE THREAD

**Issue by marz619** [sachin-handiekar/jInstagram#118]
Instagram has changed the method by which it enforces signed requests. It no longer uses the IP address.

https://instagram.com/developer/secure-api-requests/

**Comment by marz619** [comment]
@sachin-handiekar given that this was pulled in at 5c05d9369c908328b1f90953216193ab4438ef1b I had a couple of questions.

Should we completely remove any notion of Signing requests the old way?

**Comment by sachin-handiekar** [comment]
@marz619 I think it will be good to remove all the references of signing request in the code.

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
