### ISSUE TITLE
get userID from username. Not finding any function that supports this functionality. pls help.

### ISSUE THREAD

**Issue by shhrohan** [sachin-handiekar/jInstagram#123]

**Comment by marz619** [comment]
Instagram does not provide an endpoint for this...

What you can do is use the `searchUser` methods [here](https://github.com/sachin-handiekar/jInstagram/blob/master/src/main/java/org/jinstagram/Instagram.java#L356), or [here](https://github.com/sachin-handiekar/jInstagram/blob/master/src/main/java/org/jinstagram/Instagram.java#L372) and then look at the first entry. If it matches the username you put in, you can access get the ID from that object.

```java
Instagram api = new Instagram(...);

public String getIdFromUsername(String username) throws Exception {
    UserFeed search = api.searchUser(username);
    List<UserFeedData> users = search.getUserList();

    // Instagram usually returns an exact match as the first item in the list of users
    if (users.size() > 0) {
        UserFeedData user = users.get(0);
        if (user.getUserName().equalsIgnoreCase(username)) {
            return user.getId();
        }
    }
    throw new Exception("Could not find ID for username: "+username);
}
```

**Comment by shhrohan** [comment]
below code will give you userid from name 
System.out.println("Getting userid from username....");
				String myURL = "https://api.instagram.com/v1/users/search?q=" + username + "&client_id=" + clientId;
				URL url = new URL(myURL);
				InputStreamReader in = null;
				URLConnection urlConn = url.openConnection();
				StringBuilder sb = new StringBuilder();

				if (urlConn != null && urlConn.getInputStream() != null) {
					in = new InputStreamReader(urlConn.getInputStream(), Charset.defaultCharset());
					BufferedReader bufferedReader = new BufferedReader(in);
					if (bufferedReader != null) {
						int cp;
						while ((cp = bufferedReader.read()) != -1) {
							sb.append((char) cp);
						}
						bufferedReader.close();
					}
				}
				JsonParser parser = new JsonParser();
				JsonObject jsonObject = (JsonObject) parser.parse(sb.toString());
				JsonElement element = jsonObject.get("data");
				userid = element.getAsJsonArray().get(0).getAsJsonObject().get("id").getAsString();
