### ISSUE TITLE
set accesstoken to org.jinstagram.Instagram

### ISSUE THREAD

**Issue by zirconias** [sachin-handiekar/jInstagram#126]
so  i  wanted to  use your library  but only the org.jinstagram.Instagram part, 

by this i mean to  work on pojos and methods that are already set on instagram

like  instagram.getCurrentUserInfo().

but when instantiating instagram and trying to  set the token  that i  already have (using oauth strategy management that i set on mulesoft).  i found that there is no setters .

i  understand that you implemented the server flow,  and there is the verifier , token stuff.

but for those who want to use it like i described , what can we do ?

**Comment by sachin-handiekar** [comment]
Here is the code which you need -

```java
String accessToken = "Your-Access-Token";
Token token = new Token(accessToken, null);
Instagram instagram = new Instagram(token);
```
