### ISSUE TITLE
/users/self/feed  return 404 , is this api not supported ?

### ISSUE THREAD

**Issue by joe-zheng** [sachin-handiekar/jInstagram#127]
i found there is a user_media_feed interface  in ruby library , but why java failed to get information?

**Comment by tolstovdmit** [comment]
As an Instagram says /users/self/feed is deprecated now. I think this library is not updated methods yet.

More: https://www.instagram.com/developer/changelog/

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
