### ISSUE TITLE
getUserFollowList and getUserFollowedByList returns empty list

### ISSUE THREAD

**Issue by lealoureiro** [sachin-handiekar/jInstagram#128]
Hi All,

First of all thanks for the good work so far! 

I'm having a issue using method getUserFollowedByList and getUserFollowList, both of them return empty list of users... But i'm able to see my user details and i'm requesting the scope follower_list.

My code: 
            final Instagram instagram = new Instagram(accessToken);
            final UserInfoData userInfoData = instagram.getCurrentUserInfo().getData();
            final String userId = userInfoData.getId();
            final UserFeed followers = instagram.getUserFollowedByList(userId);
            final List<UserFeedData> followersList = followers.getUserList();

Am i using something wrong? Thanks for your attention,

Cheers

**Comment by tolstovdmit** [comment]
If your application is in SandBox you can interact only with users that are invited to the sandbox of your application. I was using search and i was returning empty list too. But if the search query was a part of my nickname or my mate's nickname that was added to the sandbox it showed it and only it. So, not a library problem. As I understood this was introduced around the 17th of November.

**Comment by lealoureiro** [comment]
Oh okay got it! thanks for information! Do you know what need to be done to go live ?

**Comment by tolstovdmit** [comment]
@lealoureiro, I think it'll be better if you read this guide: https://www.instagram.com/developer/sandbox/ . The last paragraph is "going live" but the rest of the paragraphs are informative too it also tells about api limitations.

**Comment by lealoureiro** [comment]
Okay! Thanks a lot for help.
