### ISSUE TITLE
Could not get access token !

### ISSUE THREAD

**Issue by azhwani** [sachin-handiekar/jInstagram#144]
Hi sachin-handiekar,
when I enter my verifier code the API returns an exception after several seconds in this line "Token accessToken = service.getAccessToken(EMPTY_TOKEN, verifier);"

The exception is 

Exception in thread "main" org.jinstagram.auth.exceptions.OAuthException: Could not get access token
Caused by: java.net.ConnectException: Connection timed out: connect

I'm using JInstagram 1.1.5

**Comment by sachin-handiekar** [comment]
Did you try out the [InstagramAuthenticationTest.java](https://github.com/sachin-handiekar/jInstagram/blob/master/src/test/java/org/jinstagram/InstagramAuthenticationTest.java) ? It shows a working example of how to get a access token using jInstagram.

**Comment by azhwani** [comment]
Thank u for your reply ! yes I have tried it before posting the issue ! I test it again right now but always the same exception !

**Comment by azhwani** [comment]
Fixed ! It was a firewall issue :) now I'm getting this exception : Exception in thread "main" org.jinstagram.auth.exceptions.OAuthException: Cannot extract an acces token. 
Response was: {"access_token": "1929026672.cef3c14.1ac38265857b45388efb3c0a00fc041a", "user": {"username": "myuser", "bio": "mybio", "website": "", "profile_picture": "src to profile pic", "full_name": "My Ful Name", "id": "myid"}}

any ideas?

**Comment by sachin-handiekar** [comment]
Use the latest version of jInstagram (1.1.6). 

The issue regarding the access token has been fixed in #151. I've released the v1.1.6 to Maven as well.

**Comment by azhwani** [comment]
ok Sir :) Thanks a lot
