### ISSUE TITLE
SessionHandler not found

### ISSUE THREAD

**Issue by ev5unleash** [sachin-handiekar/jInstagram#147]
Hi there,

While attempting to use the example: https://github.com/sachin-handiekar/jInstagram/wiki/Instagram-Realtime-API. I came across an error where I can't find the SessionHandler within jInstagram after importing with Maven. The problematic code from this page is as follows:

`        for (SubscriptionResponseObject subscriptionResponseObject : subscriptionResponseDataList) {
            // ObjectId is the name of the tag, i.e. #jinstagram
            **SessionHandler**.sendMessage(subscriptionResponseObject.getObjectId());
        }` 

Any help would be appreciated. Thanks!

**Comment by sachin-handiekar** [comment]
It was a part of this example code - https://github.com/sachin-handiekar/insta-realtime/blob/master/src/main/java/org/jinstagram/examples/SessionHandler.java
