### ISSUE TITLE
JInstagram Usage page details using user id as a long when the API details it must be a String

### ISSUE THREAD

**Issue by dan-s1** [sachin-handiekar/jInstagram#161]
The page at https://github.com/sachin-handiekar/jInstagram/wiki/jInstagram-Usage details many 
examples where it assumes the user id is a long but based on the code at 

https://github.com/sachin-handiekar/jInstagram/blob/jInstagram-1.1.6/src/main/java/org/jinstagram/Instagram.java 

user id can only be a java.lang.String.

The examples where I saw this were:
long userId = 3;
UserInfo userInfo = instagram.getUserInfo(userId);

long userId = 3;
MediaFeed mediaFeed = instagram.getRecentMediaFeed(userId);

long userId = 3;
UserFeed feed = instagram.getUserFollowList(userId);

long userId = 3;
UserFeed feed = instagram.getUserFollowedByList(userId);

long userId = 3;
RelationshipFeed feed = instagram.getUserRelationship(userId);

**Comment by sachin-handiekar** [comment]
Will update the documentation as per the code.

**Comment by abargnesi** [comment]
Fixed in document. Feel free to close @sachin-handiekar.
