### ISSUE TITLE
Pagination does not work with signed requests

### ISSUE THREAD

**Issue by worrel** [sachin-handiekar/jInstagram#166]
When enforcing signed requests, the *sig* param is included in the query string.  When using API that uses Pagination, the nextUrl contains the query params from the original call (as well as appropriate next_max_id param).

The current logic doesn't properly strip the old query string from the endpoint before signing, resulting in 403 failures when requesting the first paginated page.

The fix is to strip the query string from the nextUrl & pass that as the param map.  An additional step is to remove the old *sig* param from that map else it will get signed too, also leading to 403 failures.

Fix is implemented in #165

**Comment by sachin-handiekar** [comment]
Will push a release to Maven Central on the weekend. Let me know if there are more bugs in the library.

**Comment by worrel** [comment]
@sachin-handiekar great thanks! There is a separate PR for handling special chars see #168

**Comment by abargnesi** [comment]
@sachin-handiekar It looks like this issue was fixed (#165, #167) and released. Can this be closed?
