### ISSUE TITLE
Instagram API shut down June 1st 2016

### ISSUE THREAD

**Issue by jvence** [sachin-handiekar/jInstagram#172]
I'm assuming that this project is no longer useful as Instagram has shut down its API to 3rd-party apps.

**Comment by robsoncassol** [comment]
Direct from Instagram documentation 
"Any app created before Nov 17, 2015 will continue to function until June 1, 2016. On that date, the app will automatically be moved to Sandbox Mode if it wasn't approved through the review process. The previous version of our documentation is still available here."

**Comment by robsoncassol** [comment]
That is, you should submit your app to Review process to have a normal access to instagram API. 
This project is still very useful.

**Comment by abargnesi** [comment]
@sachin-handiekar This can be closed.

**Comment by jvence** [comment]
Has anyone have their app accepted? I don't think they are accepting 3rd party. You can submit as much as you want but they won't approve it.

**Comment by abargnesi** [comment]
See https://www.quora.com/How-long-does-it-take-Instagram-to-review-app-permissions. Folks on there have confirmed how long it took for their application to be approved.

It also seems like their can be delays or even rejection without notice.

**Comment by abargnesi** [comment]
Closing. Reopen if needed.
