### ISSUE TITLE
Invalid Integer value for key: X-Ratelimit-Remaining, value :null

### ISSUE THREAD

**Issue by martinmalek** [sachin-handiekar/jInstagram#175]
Can we confirm if instagram is still using these headers. Our graphs show this not working since 16th of June.

**Comment by jeffersonaraujo** [comment]
I'm having the same problem, I do not know what to do

**Comment by santinomazzocchi** [comment]
Hi,
we noticed that the header field "X-Ratelimit-Remaining" became
lowercase: "x-ratelimit-remaining".

I guess it's your problem.

Our dirty-solution was to use:

*Map<String, String> headers = userInfo.getHeaders()*

and look for

*headers.get("x-ratelimit-remaining")*

Bye
Santino



2016-06-28 15:59 GMT+02:00 Jefferson Araújo <notifications@github.com>:

**Comment by martinmalek** [comment]
Can we have a fix that does to lowercase or similar?

**Comment by martinmalek** [comment]
I see this was actually fixed in - https://github.com/sachin-handiekar/jInstagram/pull/160
