### ISSUE TITLE
JavaDoc?

### ISSUE THREAD

**Issue by DevDistorts** [sachin-handiekar/jInstagram#178]
Hello, I am currently making an application with this api and i am looking for a java doc for this. Is there one? JavaDocs make stuff make 10000 times easier when trying to develop with an lib that you don't know.

**Comment by abargnesi** [comment]
The `jInstagram` project does seem to have some javadoc included in the source.

You can generate it using maven:

```bash
cd jInstagram
mvn javadoc:javadoc -Dmaven.javadoc.failOnError=false
open target/site/apidocs/index.html
```

The `-Dmaven.javadoc.failOnError` helps to build the javadoc HTML even when errors are present (which there are at the moment using Java 8).

**Comment by abargnesi** [comment]
Additionally, javadocs are published to [maven central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.sachinhandiekar%22).

You can download them, if you use maven for your project, using the `-DdownloadJavadocs=true` option. See this [SO post](http://stackoverflow.com/questions/5780758/maven-always-download-sources-and-javadocs).

**Comment by abargnesi** [comment]
You can also grab the javadocs from from this site:

http://www.javadoc.io/doc/com.sachinhandiekar/jInstagram/1.1.8

@sachin-handiekar This can be closed.
