### ISSUE TITLE
Is the project still maintained? Getting errors on most functions.

### ISSUE THREAD

**Issue by Athamax** [sachin-handiekar/jInstagram#194]
I can't get an output from most functions.
For example:

`MediaInfoFeed mediaInfoFeed = instagram.getMediaInfo(media_id);`
Does not work (invalid media id, when it's perfectly valid)

> List<UserFeedData> ud = instagram.getUserFollowList("user_id").getUserList();
> 			System.out.println("Ended, found:  " + ud.size());

Also does not work. Returns size 0, when my follow list is around 1k.
**The user_id is correct**, checked against browser, API and `getCurrentUserInfo()` .

These and several other function do not work.
The auth is fine, **I have full scope** and tested things such as retrieving my own name and bio.

Is the project discontinued?

**Comment by abargnesi** [comment]
Nope. The project is actively maintained.

I would check the scope setting when you authorize the user credential (check [here](https://www.instagram.com/developer/authorization/)). For example you will need *follower_list* scope for your application to be able to read the followers of an authorized account.

If it is still not working for you I suggest you reply with a self-contained example that doesn't meet your expectations (also see [SSCCE](http://sscce.org/)). I would be glad to look at it.

**Comment by Athamax** [comment]
I'm very glad to hear this !
Then I'm probably doing something wrong, but I really don't understand what.

Here's a single-class minimal runnable example, fully commented out:
http://pastebin.com/WSTVuJVy

Thank you so much for the help.
