### ISSUE TITLE
Verifier

### ISSUE THREAD

**Issue by simpleC0de** [sachin-handiekar/jInstagram#195]
Hey there, im not quite sure how to use the verifier. Mainly, what is the content of it?

Sorry if thats not an Issue. Never worked with Instagram actively before.

Thanks for any answer! 👍

**Comment by sachin-handiekar** [comment]
@simpleC0de The verifier is a part of OAuth handshake, you can read more about it on http://oauthbible.com/  or http://wiki.oauth.net/w/page/12238555/Signed%20Callback%20URLs
