### ISSUE TITLE
How to get multiple images in one post?

### ISSUE THREAD

**Issue by z0mb1ek** [sachin-handiekar/jInstagram#204]
Cannot parse post like this https://www.instagram.com/p/BTyeqUFlSFY/ . There are 3 images in it.

**Comment by z0mb1ek** [comment]
it is new carousel type

**Comment by z0mb1ek** [comment]
i see that you merge pr for this, but it did not build

**Comment by sachin-handiekar** [comment]
Will fix it today!!

**Comment by sachin-handiekar** [comment]
Have ignored the failing test for now... so the snapshot should be fine for use. Will fix the failing test and also will release it to Maven Central later today.

**Comment by z0mb1ek** [comment]
big thx

**Comment by sachin-handiekar** [comment]
Closing the issue. Re-open if needed
