### ISSUE TITLE
Release 1.2.2

### ISSUE THREAD

**Issue by AliNield** [sachin-handiekar/jInstagram#212]
Hi there,

I submitting this change yesterday (https://github.com/sachin-handiekar/jInstagram/pull/211) and would love to see it on maven central as soon as possible. Would it be possible to get a new version released soon? It seems like it would also bring in some other recent changes: https://github.com/sachin-handiekar/jInstagram/compare/jInstagram-1.2.1...master

Thanks! Appreciate this library.

**Comment by sachin-handiekar** [comment]
Hi @AliNield 

Will release jInstagram today to Maven Central. Thanks for the PR.

Regards,
Sachin

**Comment by sachin-handiekar** [comment]
Done.
