### ISSUE TITLE
Support for GraphAPI?

### ISSUE THREAD

**Issue by martinmalek** [sachin-handiekar/jInstagram#216]
Hi,

Are you planning to support Graph API now that the old API is being deprecated?

Thanks,
Martin

**Comment by xetra11** [comment]
Hey @sachin-handiekar 
Any infos for that graph-api thing? We are relying on your library but are unsure if you will support it.

**Comment by xberger** [comment]
@xetra11
Of course ultimately @sachin-handiekar has to answer this, but he hasn't for a while on this project now.

My very strong guess is, that this project is phasing out with the classic API. I would not expect updates of jInstagram anymore. You can use https://restfb.com/ as a Graph API Java library. It's not perfect, but good enough and with an active user base. It doesn't really make sense to start a new Graph API library in my opinion anyway.

**Comment by sachin-handiekar** [comment]
Hi @xetra11 / @xberger ,

I don't have any plans to support the Instagram Graph API, as the documentation which i've seen in the past supports the business accounts and it will be quite hard to test them. 

As pointed out by @xberger, the restfb library will be your best choice.

Regards,
Sachin
