### ISSUE TITLE
Paging through User Feed

### ISSUE THREAD

**Issue by alexk307** [sachin-handiekar/jInstagram#40]
When calling the getUserFeedInfoNextPage() method with a Pagination object as the parameter, I'm getting a number format exception. The method is trying to parse a String that contains an underscore into a Long.

Full stack trace: https://gist.github.com/alexk307/8566175

**Comment by afattahi54** [comment]
@alexk307 can you please put the code you used for paging through User Feed
Did the error solved ?!
