### ISSUE TITLE
Request Timeout

### ISSUE THREAD

**Issue by santinomazzocchi** [sachin-handiekar/jInstagram#42]
Hi,
how can I set a timeout on requests?

I noticed that's the method call "setConnectTimeout" in org.jinstagram.http.Request but there's no way to use it.

I suggest to use "InstagramConfig" to pass the timeout value that will be use in org.jinstagram.Instagram.getApiResponse method.

**Comment by arinto** [comment]
It this issue solved by #44 ?

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
