### ISSUE TITLE
Use logging framework

### ISSUE THREAD

**Issue by arinto** [sachin-handiekar/jInstagram#48]
Use logging framework such as [slf4j](http://www.slf4j.org/) so that we can easily output some debugging information and error messages to log file instead of console.

**Comment by afattahi54** [comment]
+1

**Comment by afattahi54** [comment]
Will it be done, or it won't be applied ?

**Comment by sachin-handiekar** [comment]
SLF4J has been added to the pom.xml, also logging for request/response messages has been added. 

A separate issue has been raised to further improve the logging #109 .

**Comment by afattahi54** [comment]
Thanks !
