### ISSUE TITLE
Connection keep alive

### ISSUE THREAD

**Issue by slumx** [sachin-handiekar/jInstagram#51]
It looks like you're disabling http.keepAlive in the Request object. Ass the java specs says, this does affect all other connections as well if I understand the java specs correct. I can't seem to find an easy way to change this in jInstagram so maybe it should be up to the developer using your API if he want to enable/disable http.keepAlive somewhere central in the application???

**Comment by sachin-handiekar** [comment]
Fixed in current build. Added keepConnectionAlive paramter in InstagramConfig which can be then pass into Request object.
