### ISSUE TITLE
next_max_id and min_id deprecated for recent media tags

### ISSUE THREAD

**Issue by pbvahlst** [sachin-handiekar/jInstagram#52]
Instagram comes with this warning: 
"deprecation_warning": "next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead",

for the endpoint: https://api.instagram.com/v1/tags/{tagname}/media/recent

This could probably be an issue with other endpoints as well.

**Comment by mahsa2** [comment]
This issue has been closed, however, I am still getting the same error as mentioned here. I am using version 1.1.6 and receiving this error message on retrieving tags.

"pagination": {
    "next_min_id": "..",
    "deprecation_warning": "next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead",
    "min_tag_id": "..."
  },

Is this issue solved in 1.1.6?
