### ISSUE TITLE
Usage of setUserHasLiked in MediaFeedData

### ISSUE THREAD

**Issue by jtrinche** [sachin-handiekar/jInstagram#61]
Guys,
This is not really a bug but more a question regarding usage of API. I am currently testing it to see if I can make all the functionality I will need later.
I was expecting to be able to set a like on a media with something like this:

<code>List<MediaFeedData> mediaFeeds = mediaFeed.getData();</code>
<code>mediaFeeds.get(1).setUserHasLiked(true);
</code>
It seems it doesn't work as I would expect. Like is not set and I dont have any exception thrown telling me that I am doing something wrong.

Any idea what I could be doing wrong?

Thanks,
J.

**Comment by marz619** [comment]
@jtrinche @buraksahin @jtrinche please also note https://github.com/sachin-handiekar/jInstagram/issues/114#issuecomment-144767642

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
