### ISSUE TITLE
Expose raw JSON body for jInstagram client

### ISSUE THREAD

**Issue by arinto** [sachin-handiekar/jInstagram#65]
I have a use case where I need to add more fields to the Instagram data that obtained using jInstagram. For example, I need to add `location_name` field into a media instance which has `location_id` in it.

In order to effectively handle this use case, I prefer to get raw JSON body so that I can parse it as a `map` and I can add the new field accordingly.

Alternatively, we can serialize the instance returned by jInstagram into JSON string and deserialize it as a `map`. But this alternative method is ineffective since we need to perform the conversion twice. 

What do you think of this feature? If you're okay, then I can submit a pull request for this feature.

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
