### ISSUE TITLE
Pagination through the Followed-By endpoint

### ISSUE THREAD

**Issue by RafaelAlbani** [sachin-handiekar/jInstagram#68]
Hi, i need to know if there is a way to paginate the followed-by endpoint, using the getUserFollowedByList method, because the first call to this endpoint return just 50 followers. 

Thanks in advance

**Comment by shhrohan** [comment]
can u post a snippet.. how to make work ?

**Comment by RafaelAlbani** [comment]
Sure @shhrohan, let me open my IDE and grab an example.

**Comment by RafaelAlbani** [comment]
In the last versions of the library, it was introduced a new method "Instagram.getUserFollowedByListNextPage" that makes the pagination even more easy, below i provide an example:

```java
Pagination pagination = null;

do {
	UserFeed userFeed;
	if(pagination == null) {
		userFeed = instagram.getUserFollowedByList(idProfile);
	} else {
		userFeed = instagram.getUserFollowedByListNextPage(pagination);
	}

	pagination = userFeed.getPagination();
	List<UserFeedData> users = userFeed.getUserList();

	for(UserFeedData user : users) {	
	}

} while (pagination.getNextUrl() != null);
```

So, basically what i do in the code below is iterating through the pages, using the  "pagination.getNextUrl()" as an indicator of the final of the followers list for the the profile provided.

Let me know if it works for you.

**Comment by shhrohan** [comment]
@RafaelAlbani  It worked like charm. Thanks a lot for the help  :+1:

**Comment by shhrohan** [comment]
one more question... 
how to tell using the user id that when the user having that userid was last online  or liked a photo..

**Comment by RafaelAlbani** [comment]
Hum, when you say "last online" what do you really mean?

And about the like, when you retrieve the likes for a photo, you don't have the date of the like itself, so it is hard to figure out this kind of information. 
You can know if the user that likes a photo is following the profile that post the photo, comparing the userid of the like with the followers that you have retrieved.

I hope it helps
