### ISSUE TITLE
Getting api rate limits fails / treat header fields case-insensitive

### ISSUE THREAD

**Issue by xberger** [sachin-handiekar/jInstagram#79]
Hi,

when calling InstagramObject.getAPILimitStatus() / InstagramObject.getRemainingLimitStatus() always -1 is returned. Turns out the implementation of HttpURLConnection (com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection) is converting the headers to lower-case and thus looking them up via key in the hashmap fails.

My first thought was to blame the HttpURLConnection implementation. But as it seems http headers are meant to be case-insensitive ( http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive ). So can't really blame them.

Maybe storing the headers using a java.util.TreeMap with a String.CASE_INSENSITIVE_ORDER comparator could fix this issue? As a quickfix I will work around with InstagramObject.getHeaders().

Regards,
xberger

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
