### ISSUE TITLE
WIKI - List of projects using jInstagram

### ISSUE THREAD

**Issue by sachin-handiekar** [sachin-handiekar/jInstagram#83]
WIKI - List of projects using jInstagram

**Comment by slumx** [comment]
digitalfootprints.dk

**Comment by zorrobiwan** [comment]
tweetwallpro.com

**Comment by sachin-handiekar** [comment]
Added page in Wiki - https://github.com/sachin-handiekar/jInstagram/wiki/Projects-using-jInstagram

**Comment by mkorobeynikov** [comment]
ruslanradriges.com

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
