### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by MikOfClassX** [sachin-handiekar/jInstagram#86]
Hi, I have improved JInstagram to support proxy.

Here the code of the Request.class  :

	/**
	 * Proxy should be enabled by the following System properties: "http.proxyPort", "http.proxyHost"
	 * 
	 * @return a Proxy instance using the System properties or null.
	 *         If the System properties are not valid the Proxy instance fails then return null
	 */
	public static final Proxy getProxy()
	{
		Proxy ret = Proxy.NO_PROXY;

		
		try
		{
			final String host = System.getProperty("http.proxyHost");
			final String port = System.getProperty("http.proxyPort");

			// setup proxy
			if ((host != null) && (port != null))
			{
				final InetSocketAddress proxyLocation = new InetSocketAddress(host, Integer.parseInt(port));
				ret = new Proxy(Proxy.Type.HTTP, proxyLocation);
			}
		}
		catch (Throwable e)
		{
			e.printStackTrace();
		}

		return ret;

        }

	/**
	 * Proxy should be enabled by the following System properties: "http.proxyPort", "http.proxyHost"
	 * 
	 * @return a Proxy instance using the System properties or null.
	 *         If the System properties are not valid the Proxy instance fails then return null
	 */
	private void createConnection() throws IOException
 	{
		String effectiveUrl = URLUtils.appendParametersToQueryString(url,
				querystringParams);

		if (connection == null) {
			System.setProperty("http.keepAlive", connectionKeepAlive ? "true"
					: "false");

			connection = (HttpURLConnection) new URL(effectiveUrl)
					.openConnection(getProxy());
					
			connection.setConnectTimeout(connectTimeout);
			connection.setReadTimeout(readTimeout);
		}
	}

What about it? Can be imported into the next release?

Cheers,
Fabio

**Comment by sachin-handiekar** [comment]
Can you send me a pull request on Github.

**Comment by MikOfClassX** [comment]
Sorry but I'm not familiar with the pull request. I never do it before.

**Comment by pa7751** [comment]
Can you demonstrate a usage of this please. Every time I try to use this, using proxy, I get SocketCLosedException
