### ISSUE TITLE
instagram.getUserFeeds().getData()

### ISSUE THREAD

**Issue by afattahi54** [sachin-handiekar/jInstagram#87]
Consider the sample application and please look at gallery.jsp page ....

The page uses instagram.getUserFeeds().getData() to get the mediaList. It returns around 18-20 pages.

How is it possible to use jInstagram to get the previous user feeds. I found that there is a method (instagram.getUserFeeds().getPagination() ) But I could not find how to use it ?!

Regards

**Comment by fabriziomorello** [comment]
Searching for the answer to this too !

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
