### ISSUE TITLE
oAuth Access Token

### ISSUE THREAD

**Issue by jeromekwek** [sachin-handiekar/jInstagram#88]
Is there a possibility of creating an Instagram object based on the the access token of the logged in user?

I'm using the AndroidInstagram (https://github.com/lorensiuswlt/AndroidInstagram) library to authorize the user, and the access token I am getting is in the form: 13332854.5309b05.9f09afe5c37a4a118fce2e6bbff07b6c

Otherwise, is there anyway jInstagram can support the authentication of the user without them entering a verification code like the example provided?

**Comment by jeromekwek** [comment]
The snippet below is what I'm trying out with both libraries:

net.londatiga.android.instagram.Instagram mInstagram = new net.londatiga.android.instagram.Instagram(this, AppData.CLIENT_ID, AppData.CLIENT_SECRET, AppData.REDIRECT_URL);
        InstagramSession mInstagramSession = mInstagram.getSession();

        if (!mInstagramSession.isActive()) {
            mInstagram.authorize(mAuthListener);
        }
        else {
            instagram = new Instagram(mInstagramSession.getAccessToken(), AppData.CLIENT_SECRET, AppData.CALLBACK_URL);
        }

But I'm getting the error:

 java.lang.NoSuchMethodError: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/ext.jar)
            at org.jinstagram.utils.EnforceSignedHeaderUtils.signature(EnforceSignedHeaderUtils.java:26)
            at org.jinstagram.Instagram.createEnforceSignatrue(Instagram.java:979)

**Comment by sachin-handiekar** [comment]
You can use the following code to create an Instagram object based on the access token -

```java
String ACCESS_TOKEN = "[Add your access token here]";
Token token = new Token(ACCESS_TOKEN, null);
Instagram instagram = new Instagram(token);
```

**Comment by jeromekwek** [comment]
Thanks for the tip! Worked perfect! :+1:

**Comment by ahmedmagdy95** [comment]
String ACCESS_TOKEN = "[Add your access token here]";
Token token = new Token(ACCESS_TOKEN, null);
Instagram instagram = new Instagram(token); 
I've tried this solution and it doesn't work for me i get OAuthAccessTokenException: The access_token provided is invalid.

**Comment by mahmoudhanafy** [comment]
@ahmedlhanafy try to test your access token with sending simple get request using tool like postman.
GET `https://api.instagram.com/v1/tags/cat/media/recent?access_token=[YOUR TOKEN]`
