### ISSUE TITLE
Error parsing json to object type org.jinstagram.entity.tags.TagMediaFeed

### ISSUE THREAD

**Issue by PepijnK** [sachin-handiekar/jInstagram#9]
Hi,

First of all thanks for the effort for creating and maintaining the lib! 
We are using the lib to scrape instagram feeds based on hashtags. In general it works quite nicely, but I have a weird issue that on some of our servers the scraping of some feeds (not all!) fail with an InstagramException: "Error parsing json to object type org.jinstagram.entity.tags.TagMediaFeed". Now I wonder if this is a configuration issue or something else.

Many thanks,
pepijn

**Comment by marcbr8** [comment]
Having this same problem here
