### ISSUE TITLE
Creating a real time application

### ISSUE THREAD

**Issue by vish2487** [sachin-handiekar/jInstagram#97]
Dear Sachin,

At the outset thank you for creating this API..its a life saver.. I am trying to create a real time application and get the live feeds and process the tags to find out trending tags...
1. I created a demo app which authenticates the client Id and key and gives me a code which I paste in the console and get the data. Now this has to pasted each time to get a code so can this be done automatically.
2. I need to extract the information in a JSON format so that I can process it using the Kafka and Storm blocks...how do I go about doing this.

TIA
Regards
Viswanath

**Comment by sachin-handiekar** [comment]
Have a look at this example - https://github.com/sachin-handiekar/insta-realtime

You might have to tweak it a little bit as per your need. The example uses the jInstagram library and Websocket for showing realtime feed for a specific tag.

**Comment by vish2487** [comment]
Hey Sachin,

Sorry to bother you like this.I appreciate your speedy response. I will
definitely go through the example. My moot issue is to handle the feeds in
a real time system. So I am building a system to give me the feeds from the
Instagram API as a JSON and then utilize the Storm architecture to do a
sentiment analysis on the feeds. Any ideas on how to go about doing that.
If you can guide me as to how to get the data into a JSON and store it,
that will solve my problem to a great extent.

Cheers
Viswanath

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
