### ISSUE TITLE
Log Instagram API call

### ISSUE THREAD

**Issue by afattahi54** [sachin-handiekar/jInstagram#98]
Is it possible to log the Instagram API calling (request and response)

**Comment by alatushkin** [comment]
As far as i see - no. You cant log request and response without modification of sources of lib. But changes are minor and simple.

**Comment by afattahi54** [comment]
I think it would be quite useful if the jInstagram could log the underline request and response. (even in pretty json format :) )

**Comment by sachin-handiekar** [comment]
Will try to add the req/response logging by end of this week.

Or if someone can do it and send me a PR that would be great...

**Comment by sachin-handiekar** [comment]
Added logging for request/response in the current build.

**Comment by afattahi54** [comment]
thanks !
